name = "DiffinDiffs"
uuid = "1c15b2bf-cfaa-4a64-9ed6-b84bdd745e5c"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.1.0"

[deps]
DiffinDiffsBase = "7fc23ce2-6e83-4e3c-822f-a79085ccb3e8"
InteractionWeightedDIDs = "4fda0319-85a0-4a01-849e-821b918731ee"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DiffinDiffsBase = "0.4"
Documenter = "0.27"
InteractionWeightedDIDs = "0.3"
Reexport = "0.2, 1"
julia = "1.3"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Pkg", "Test"]
