name: CI-stable
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
    tags: '*'
jobs:
  test:
    name: ${{ matrix.package }} - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    env:
      JULIA_NUM_THREADS: 2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - DiffinDiffsBase
          - InteractionWeightedDIDs
        version:
          - '1'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - x64
        include:
          - package: DiffinDiffs
            version: '1'
            os: ubuntu-latest
            arch: x64
          - package: DiffinDiffsBase
            version: '1.3'
            os: ubuntu-latest
            arch: x64
          - package: InteractionWeightedDIDs
            version: '1.3'
            os: ubuntu-latest
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Develop lib packages
        run: julia --project=. -e "using Pkg; lib = joinpath(@__DIR__, \""lib\""); paths = joinpath.(lib, readdir(lib)); foreach(x->Pkg.develop(PackageSpec(path=x)), paths)"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          TEST_TARGET: ${{ matrix.package }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,lib/DiffinDiffsBase/src,lib/InteractionWeightedDIDs/src
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
