name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.SSH_KEY }}
          user: junyuan-chen
          email: 37969042+junyuan-chen@users.noreply.github.com
          gpg: ${{ secrets.GPG_KEY }}
          gpg_password: ${{ secrets.GPG_PASSWORD }}
